name: publish
on:
  push:
    branches:
      - main
    paths:
      - '**publish.yml'
      - '**.rockspec'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master
    - uses: joelvaneenwyk/gh-actions-lua@v9
      with:
        luaVersion: "5.1.5"
    - uses: joelvaneenwyk/gh-actions-luarocks@v4
    - name: install upload deps
      run: luarocks install lua-cjson && luarocks install luasec
    - name: publish
      env:
        ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
      run: luarocks upload --force --api-key=${{ env.LUAROCKS_API_KEY }} ${{ env.ROCKSPEC }}
