name: publish
on:
  push:
    branches:
      - main
    paths:
      - '**publish.yml'
      - '**.rockspec'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SYSDEPS: build-essential make cmake git curl libssl-dev ssl-cert
      ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
      LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
    steps:
    - uses: actions/checkout@v4
    - uses: joelvaneenwyk/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"
    - uses: joelvaneenwyk/gh-actions-luarocks@v4
    - name: system dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ env.SYSDEPS }}
    - name: install upload deps
      run: luarocks install lua-cjson && luarocks install luasec
    - name: publish
      run: luarocks upload --force --api-key=${{ env.LUAROCKS_API_KEY }} ${{ env.ROCKSPEC }}
