name: test
on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
      - '**.t'
      - '**test.yml'
      - '**.rockspec'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "luajit", "luajit-openresty"]
    env:
      DEV: --dev
      SYSDEPS: build-essential make cmake git libnginx-mod-http-lua cpanminus curl libssl-dev ssl-cert libmongoc-dev
      CPANDEPS: Test::Nginx::Socket::Lua https://github.com/luatoolz/App-Prove-Plugin-NginxModules.git
      ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
    steps:
    - uses: actions/checkout@master
    - uses: jkl1337/gh-actions-lua@v11
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: jkl1337/gh-actions-luarocks@v5
    - name: system dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ env.SYSDEPS }}
    - name: disable system nginx
      run: sudo systemctl disable nginx && sudo systemctl stop nginx && sudo chmod 666 /var/log/nginx/*
    - name: test deps
      run: luarocks install ${{ env.DEV }} t-storage-mongo && luarocks install ${{ env.DEV }} luacheck && luarocks install ${{ env.DEV }} busted
    - name: cpanm dependencies
      run: sudo cpanm ${{ env.CPANDEPS }}
    - name: dependencies
      run: luarocks install --deps-mode all --only-deps ${{ env.DEV }} ${{ env.ROCKSPEC }}
    - name: build
      run: luarocks build --deps-mode all ${{ env.DEV }} ${{ env.ROCKSPEC }}
    - name: docker compose up
      run: docker compose up -d --wait --wait-timeout 10 --no-log-prefix
    - name: docker logs
      run: docker compose logs && docker compose ps
    - name: test
      run: luarocks test
    - name: docker compose down
      run: docker compose down --remove-orphans -v
